# Generated by Django 2.2.12 on 2020-08-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='title',
            field=models.CharField(default='Hello!', max_length=120),
        ),
    ]
